### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "rafalb92@ironoak.pl",
  "password": "supersecret123"
}

### Get Me
GET http://localhost:3000/auth/me

### Refresh Token
POST http://localhost:3000/auth/refresh

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "rafalb92@ironoak.pl",
  "password": "supersecret123"
}

### Logout
POST http://localhost:3000/auth/logout

### Products
GET http://localhost:3000/products
### Products with variant
GET http://localhost:3000/products?variantId=e0fa09d5-f34d-4827-93f1-7f8e2a2d2499

### Get Cart
GET http://localhost:3000/cart
### Remove all items from cart
DELETE http://localhost:3000/cart/items/06502491-8e82-4389-be3e-708c36906517
### Add item to cart
POST http://localhost:3000/cart/items
Content-Type: application/json

{
  "productVariantId": "e0fa09d5-f34d-4827-93f1-7f8e2a2d2499",
  "quantity": 2
}

### Update item quantity in cart
PATCH http://localhost:3000/cart/items/e0fa09d5-f34d-4827-93f1-7f8e2a2d2499
Content-Type: application/json

{
  "quantity": 4
}

### Checkout
POST http://localhost:3000/cart/checkout
Content-Type: application/json

{
  "deliveryAddress": {
    "street": "123 Main St",
    "buildingNumber": "Apt",
    "apartmentNumber": "4B",
    "city": "Anytown",
    "postalCode": "12345",
    "country": "USA"
  }
}

### Orders
GET http://localhost:3000/orders