// This file was generated by MikroORM CLI. Do not edit manually.
// Re-run `mikro-orm discovery:export` to update.

import { AccountSchema } from './modules/identity/domain/account.entity';
import { CategorySchema } from './modules/catalog/entities/category.entity';
import { ProductImageSchema } from './modules/catalog/entities/product-image.entity';
import { ProductSchema } from './modules/catalog/entities/product.entity';
import { ProductVariantSchema } from './modules/catalog/entities/product-variant.entity';
import { UserSchema } from './modules/identity/domain/user.entity';
import { EntityManager as DriverEntityManager } from '@mikro-orm/postgresql';

export const entities = [
  AccountSchema,
  CategorySchema,
  ProductImageSchema,
  ProductSchema,
  ProductVariantSchema,
  UserSchema,
] as const;

export type Database = typeof entities;

export type EntityManager = DriverEntityManager & { '~entities': Database };
export const EntityManager = DriverEntityManager;
